name = "Thems The Rules"
author = "kodiitulip"
version = "1.6.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e83794b636bd0597e69766f700f75b5e90e7e3ad53416b1bf43f4a02cd0b07da"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.230"

[options]
datapack-folder = "datapacks"
