name = "Thems The Rules"
author = "kodiitulip"
version = "2.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ce3302f00f306f7d3eab8f4c271ec5a25e8c5ce9bf314035bc8865b3e7795972"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.233"

[options]
datapack-folder = "datapacks"
