name = "Thems The Rules"
author = "kodiitulip"
version = "2.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b350cde2cdb0e51935d454543926289aac22bbd11048783a6ad9f3111d56119d"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.233"

[options]
datapack-folder = "datapacks"
