name: Export Modpack

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

defaults:
  run:
    shell: nu {0}

env:
  modrinth-project-id: "NrOJ6Iod"

jobs:
  export:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: hustcer/setup-nu@v3
        with:
          version: "0.111.0"
          enable-plugins: true

      - name: Get Info
        id: info
        run: |
          let pack = (open ./pack.toml)
          let changelog = (open ./CHANGELOG-LATEST.md | lines | skip 5 | str join "\n")
          if (not ("out" | path exists)) { mkdir out }
          $"version=($pack.version)
          loaders=($pack.versions | columns | where ($it != "minecraft") | to json -r)
          game-versions=($pack.versions.minecraft)
          name=($pack.name)
          name-kebab=($pack.name | str kebab-case)
          outfile=out/($pack.name | str kebab-case).mrpack
          changelog<<CHG
          ($changelog)
          CHG" | save -a $env.GITHUB_OUTPUT

      - uses: vspr-sh/packwiz-setup-action@master
      - name: Packwiz export
        run: ^packwiz modrinth export -o ${{ steps.info.outputs.outfile }}

      - name: Upload package to workflow artifacts
        uses: actions/upload-artifact@v6
        with:
          path: ${{ steps.info.outputs.outfile }}
          name: ${{ steps.info.outputs.name-kebab }}.mrpack
          retention-days: 1

      - name: Upload package to GitHub release
        uses: ncipollo/release-action@v1.20.0
        with:
          allowUpdates: true
          artifactErrorsFailBuild: true
          artifacts: ${{ steps.info.outputs.outfile }}
          artifactContentType: zip
          bodyFile: ./CHANGELOG-LATEST.md
          tag: ${{ steps.info.outputs.version }}
          name: ${{ steps.info.outputs.name }}-${{ steps.info.outputs.game-versions }}-${{ steps.info.outputs.version }}
