name: Export Modpack

on:
  workflow_dispatch:
    inputs:
      modrinth-release:
        type: boolean
        default: false
        description: Publish Modrinth Release

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

defaults:
  run:
    shell: nu {0}

env:
  modrinth-project-id: ""

jobs:
  export:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: hustcer/setup-nu@v3
        with:
          version: "*"
          enable-plugins: true

      - name: Get Info
        id: info
        run: |
          use modlist.nu
          let pack = (open ./pack.toml)
          let changelog = modlist changelog | str trim
          let listofmods = ["\n" (modlist details)] | str join "\n"
          $changelog | save -f bodyfile.md
          $listofmods | save -a bodyfile.md
          if (not ("out" | path exists)) { mkdir out }
          $"version=($pack.version)
          loaders=($pack.versions | columns | where ($it != "minecraft") | to json -r)
          game-versions=($pack.versions.minecraft)
          name=($pack.name)
          name-kebab=($pack.name | str kebab-case)
          outfile=out/($pack.name | str kebab-case).mrpack
          changelog<<CHG
          ($changelog)
          CHG" | save -a $env.GITHUB_OUTPUT

      - uses: vspr-sh/packwiz-setup-action@master
      - name: Packwiz export
        run: ^packwiz modrinth export -o ${{ steps.info.outputs.outfile }}

      - name: Upload package to workflow artifacts
        uses: actions/upload-artifact@v6
        with:
          path: ${{ steps.info.outputs.outfile }}
          name: ${{ steps.info.outputs.name-kebab }}.mrpack
          retention-days: 1

      - name: Upload package to GitHub release
        uses: ncipollo/release-action@v1.20.0
        with:
          allowUpdates: true
          artifactErrorsFailBuild: true
          artifacts: ${{ steps.info.outputs.outfile }}
          artifactContentType: zip
          bodyFile: ./bodyfile.md
          tag: ${{ steps.info.outputs.version }}
          name: ${{ steps.info.outputs.name }}-${{ steps.info.outputs.game-versions }}-${{ steps.info.outputs.version }}

      - if: env.modrinth-project-id != ''
        uses: cloudnode-pro/modrinth-publish@v2
        with:
          token: ${{ secrets.MODRINTH_TOKEN }}
          project: ${{ env.modrinth-project-id }}
          version: ${{ steps.info.outputs.version }}
          loaders: ${{ steps.info.outputs.loaders }}
          game-versions: ${{ steps.info.outputs.game-versions }}
          files: ${{ steps.info.outputs.outfile }}
          name: ${{ steps.info.outputs.name }}-${{ steps.info.outputs.game-versions }}-${{ steps.info.outputs.version }}
          changelog: ${{ steps.info.outputs.changelog }}
